# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.10.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  SignTool: C:\Program Files (x86)\Windows Kits\10\bin\x64

# scripts that run after cloning repository
install:
  # clone the submodules
  - cmd: git submodule update --init --recursive

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
# before_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
# before_package:

# scripts to run after build
# after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild /nologo /maxcpucount /verbosity:quiet /consoleloggerparameters:NoItemAndPropertyList;NoSummary;Verbosity=minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild /nologo /maxcpucount /verbosity:quiet /consoleloggerparameters:NoItemAndPropertyList;NoSummary;Verbosity=minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: Win32
  - path: x64
